name: Rust

on: [push]

jobs:
  build_and_test:
    name: Simulation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          toolchain: nightly
