name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          toolchain: nightly
          command: test
